source 'https://rubygems.org'

gem 'sfn'
gem 'sparkle-pack-aws-my-s3-buckets',      :git => 'https://github.com/gswallow/sparkle-pack-aws-my-s3-buckets.git'
gem 'sparkle-pack-aws-my-security-groups', :git => 'https://github.com/gswallow/sparkle-pack-aws-my-security-groups.git'
gem 'sparkle-pack-aws-my-sns-topics',      :git => 'https://github.com/gswallow/sparkle-pack-aws-my-sns-topics.git'
gem 'sparkle-pack-aws-ebs-volumes',        :git => 'https://github.com/gswallow/sparkle-pack-aws-ebs-volumes.git'
gem 'sparkle-pack-aws-my-subnets',         :git => 'https://github.com/gswallow/sparkle-pack-aws-my-subnets.git'
gem 'sparkle-pack-aws-availability-zones'
gem 'sparkle-pack-cfn-init-chef',          :git => 'https://github.com/gswallow/sparkle-pack-cfn-init-chef.git'
